#!/bin/sh
set -eu
cd "$(dirname "$0")/.."
.venv/bin/python manage.py test rc --settings=recast.test_settings
.venv/bin/python manage.py check --settings=recast.test_settings
.venv/bin/python manage.py makemigrations --check --dry-run --settings=recast.test_settings
git diff --check
