# Generated by Django 2.2.1 on 2019-05-30 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='is_cloudflare',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='source',
            name='last_302_url',
            field=models.CharField(default=' ', max_length=255),
        ),
    ]
