# Generated by Django 2.2.1 on 2019-06-20 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rc', '0002_auto_20190530_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='found',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='due_poll',
            field=models.DateTimeField(default='1900-01-01 00:00:00'),
        ),
        migrations.AlterField(
            model_name='source',
            name='last_302_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='last_302_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
