# Generated by Django 5.2.17 on 2026-09-11 11:21

from django.db import migrations, models


def seed_quota(apps, schema_editor):
    apps.get_model("rc", "DiscoveryQuota").objects.using(schema_editor.connection.alias).create(pk=1)


class Migration(migrations.Migration):

    dependencies = [
        ('rc', '0003_auto_20230116_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveryQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sources_created', models.PositiveIntegerField(default=0)),
                ('lease_token', models.CharField(blank=True, default='', max_length=32)),
                ('lease_until', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiscoveryAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(db_index=True)),
                ('quota', models.ForeignKey(on_delete=models.CASCADE, related_name='discovery_attempts', to='rc.discoveryquota')),
            ],
        ),
        migrations.RunPython(seed_quota, migrations.RunPython.noop),
    ]
