# Generated by Django 2.2.1 on 2019-06-20 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rc', '0003_auto_20190620_0919'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='enclosure',
            table='feeds_enclosure',
        ),
        migrations.AlterModelTable(
            name='post',
            table='feeds_post',
        ),
        migrations.AlterModelTable(
            name='source',
            table='feeds_source',
        ),
    ]
